import Head from "next/head";
import Image from "next/image";
import {styled,keyframes} from 'styled-components'
import Navbar from "@/components/Navbar";
import { useRouter } from "next/router";

/*
* This is the landing page for my website (HOME)
* It consists of the navbar, a picture of the store, a motto, a section displaying reviews, and a button to navigate to admin page
* The owner of the business can access the admin log-in page from here.
*/

//button function to navigate to the admin log-in page
export default function Home() {

  const router = useRouter();

    function goToAdmin(){
        router.push("/adminLogin");
    }

  return (
    <>
      <Head>
       <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <ParentContainer>
        <Navbar />
        <ImageContainer>
          <ImageWrapper>
            <Image 
              src = "/storefront.webp"
              alt="Picture of the store"
              fill={true}
              />
          </ImageWrapper>

          <Motto>Savor the Spice of Life: Your One-Stop Destination for Authentic Flavors and Fresh Delights!</Motto>

        </ImageContainer>

        <ReviewContainer>

          <HeadContainer>Popular Reviews</HeadContainer>

          <Review>
            "This is the best indian store in Scranton. You can find everything regarding indian grocery. The owner has good nature and very polite. Price is so reasonable. He carries all stuff is so good. He has exchange and return policy. Overall 😊 Good." ~ Mili Shah
          </Review>

          <Review>
            "All indian groceries you can get here" ~ Shailendra Singh
          </Review>

          <Review>
            "Nice place to shop Indian groceries" ~ Sanav S
          </Review>

        </ReviewContainer>
        <FooterContainer>
          
          <NavigationButtonHolder>
            <NavigationElement onClick={goToAdmin}> 
              Admin
            </NavigationElement>
          </NavigationButtonHolder>

        </FooterContainer>

      </ParentContainer>
    </>
  )
}

//fading animation for cool effect
const fade = keyframes`
  from{
      opacity: 0.1;
  }

  to{
      opacity: 1;
  }
`
//body
const ParentContainer = styled.main`
  width: 100vw;
  height: 100vh;
`

//stores the admin log in button
const FooterContainer = styled.div`
  width: 100vw;
  height: 4vh;
  background-color: #141e30;
  color: white;
  padding-left: 5px;
  padding-bottom: 5px;
`

//the image itself
const ImageWrapper = styled.div`
  width: 70%;
  height: 75%;
  position: relative;
  object-fit: contain;
  animation: ${fade} 0.5s ease;
`

//container that holds the image
const ImageContainer = styled.div`
  display: flex;
  justify-content: left;
  align-items: center;
  padding-left: 100px;
  width: 100%;
  height: 85.65vh;
  background-color: #141e30;
`
//text styling for the motto
const Motto = styled.p`
  padding-left: 40px;
  padding-right: 15px;
  font-size: 25px;
  font-family: Sans-Serif;
  font-style: italic;
  background: linear-gradient(45deg, #ff8a00, #e52e71);
  -webkit-background-clip: text;
  color: transparent;
`
//storage for the review portion
const ReviewContainer = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  padding-left: 100px;
  padding-right: 100px;
  width: 100%;
  height: 45vh;
  background-color: #141e30;
`
//used to add a header for the review portion of the page
const HeadContainer = styled.h1`
  display: flex;
  flex-direction: column;
  align-items: center;
  font-size: 50px;
  font-family: Sans Seriff;
  text-decoration: underline;
  color: white;
`
//the reviews themselves
const Review = styled.p`
  margin: 20px;
  font-size: 20px;
  right-padding: 50px;
  font-family: Sans Seriff;
  color: white;
`

//button holder
const NavigationButtonHolder = styled.div`
  display: flex;
  justify-content: center;
  align-items: center;
  width: 5vw;
`

//the button itself
const NavigationElement = styled.button`
  padding: 0.1vw;
  background-color: white;
  border-radius: 0.5vw;
  border: none;
  cursor: pointer;

  transition: 0.1s ease-in-out;
  &:hover{
      color: red;
  }
`