import Head from "next/head";
import Image from "next/image";
import {styled,keyframes} from 'styled-components'
import Navbar from "@/components/Navbar";

/*
* This is the landing page for my website (HOME)
* It consists of the navbar, a picture for visual appeal, and a motto to grasp the users attention
*/

//button function to navigate to the admin log-in page
export default function Home() {

  return (
    <>
      <Head>
       <title>Deep-Minting</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <ParentContainer>
        <Navbar />
        <ImageContainer>
          <ImageWrapper>
            <Image 
              src="/homeimage.webp"
              alt="Landing Page Image"
              fill={true}
            />
          </ImageWrapper>
          <Motto>Dive into the world of breathtaking works of art!</Motto>
        </ImageContainer>

      </ParentContainer>
    </>
  )
}

//fading animation for cool effect
const fade = keyframes`
  from {
    opacity: 0.1;
  }

  to {
    opacity: 1;
  }
`
//body
const ParentContainer = styled.main`
  width: 100vw;
  height: 100vh;
  vertical-align: middle;
`

//the image itself
const ImageWrapper = styled.div`
  width: 55%;
  height: 75%;
  position: relative;
  object-fit: contain;
  border-radius: 30px;
  animation: ${fade} 0.5s ease;
`

//container that holds the image
const ImageContainer = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  width: 100%;
  height: 85.65vh;
  background: black;
`

//text styling for the motto
const Motto = styled.p`
  margin-top: 20px; 
  font-size: 25px;
  font-family: Sans-Serif;
  font-style: italic;
  background: #00BFFF;
  -webkit-background-clip: text;
  color: transparent;
  text-align: center;
`;
