import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styled from 'styled-components';
import Navbar from "@/components/Navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <ParentContainer>
        <Navbar />
        <ImageContainer>
          <ImageWrapper>
            <Image 
              src = "/storefront.webp"
              alt="Picture of the store"
              fill={true}
              />
          </ImageWrapper>

          <Motto>Savor the Spice of Life: Your One-Stop Destination for Authentic Flavors and Fresh Delights!</Motto>

        </ImageContainer>

        <ReviewContainer>

          <HeadContainer>Popular Reviews</HeadContainer>

          <Review>
            "This is the best indian store in Scranton. You can find everything regarding indian grocery. The owner has good nature and very polite. Price is so reasonable. He carries all stuff is so good. He has exchange and return policy. Overall 😊 Good." ~ Mili Shah
          </Review>

          <Review>
            "All indian groceries you can get here" ~ Shailendra Singh
          </Review>

          <Review>
            "Nice place to shop Indian groceries" ~ Sanav S
          </Review>

        </ReviewContainer>
        <FooterContainer>link</FooterContainer>

      </ParentContainer>
    </>
  )
}

const ParentContainer = styled.main`
  width: 100vw;
  height: 100vh;
`

const FooterContainer = styled.div`
  width: 100vw;
  background-color: #141e30;
  color: white;
  padding-left: 5px;
  padding-bottom: 5px;
`

//the image itself
const ImageWrapper = styled.div`
  width: 70%;
  height: 75%;
  position: relative;
  object-fit: contain;
`

//container that holds the image
const ImageContainer = styled.div`
  display: flex;
  justify-content: left;
  align-items: center;
  padding-left: 100px;
  width: 100%;
  height: 85.65vh;
  background-color: #141e30;
`
const Motto = styled.p`
  padding-left: 40px;
  padding-right: 15px;
  font-size: 25px;
  font-family: Sans-Serif;
  font-style: italic;
  color: red;
`

const ReviewContainer = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  padding-left: 100px;
  padding-right: 100px;
  width: 100%;
  height: 45vh;
  background-color: #141e30;
`

const HeadContainer = styled.h1`
  display: flex;
  flex-direction: column;
  align-items: center;
  font-size: 50px;
  font-family: Sans Seriff;
  text-decoration: underline;
  color: white;
`

const Review = styled.p`
  margin: 20px;
  font-size: 20px;
  right-padding: 50px;
  font-family: Sans Seriff;
  color: white;
`